"""
Firefox cookie extraction for yt-dlp.

Reads cookies from Firefox's cookies.sqlite database and writes them
in Netscape cookie format for yt-dlp to consume.
"""

import os
import shutil
import sqlite3
import tempfile
import time
import glob

_cookie_cache = {"path": None, "timestamp": 0}
_COOKIE_TTL = 1800  # 30 minutes


def _find_firefox_cookies_db() -> str | None:
    """Locate the Firefox cookies.sqlite file."""
    patterns = [
        os.path.expanduser("~/.mozilla/firefox/*/cookies.sqlite"),
        os.path.expanduser("~/snap/firefox/common/.mozilla/firefox/*/cookies.sqlite"),
        os.path.expanduser("~/.var/app/org.mozilla.firefox/.mozilla/firefox/*/cookies.sqlite"),
    ]
    for pattern in patterns:
        matches = glob.glob(pattern)
        if matches:
            return matches[0]
    return None


def _extract_cookies(db_path: str, output_path: str) -> int:
    """
    Copy cookies.sqlite to a temp file (Firefox locks it) and extract
    YouTube/Google cookies into Netscape format.
    """
    tmp_db = shutil.copy2(db_path, tempfile.mktemp(suffix=".sqlite"))
    try:
        conn = sqlite3.connect(f"file:{tmp_db}?mode=ro&immutable=1", uri=True)
        cur = conn.cursor()
        cur.execute("""
            SELECT host, isHttpOnly, path, isSecure, expiry, name, value
            FROM moz_cookies
            WHERE host LIKE '%youtube%'
               OR host LIKE '%google%'
               OR host LIKE '%ytimg%'
        """)
        rows = cur.fetchall()
        conn.close()
    finally:
        if os.path.exists(tmp_db):
            try:
                os.unlink(tmp_db)
            except OSError:
                pass

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by AquaMusic\n\n")
        for host, httponly, path, secure, expiry, name, value in rows:
            prefix = "#HttpOnly_" if httponly else ""
            subdomain = "TRUE" if host.startswith(".") else "FALSE"
            secure_s = "TRUE" if secure else "FALSE"
            if expiry:
                try:
                    exp_val = int(expiry)
                    if exp_val > 10_000_000_000_000:
                        exp_val //= 1_000_000
                    elif exp_val > 10_000_000_000:
                        exp_val //= 1_000
                    expiry_s = str(exp_val)
                except (ValueError, TypeError):
                    expiry_s = "0"
            else:
                expiry_s = "0"

            clean_val = str(value or "").replace("\r", "").replace("\n", "")
            f.write(
                f"{prefix}{host}\t{subdomain}\t{path}\t{secure_s}\t{expiry_s}\t{name}\t{clean_val}\n"
            )

    return len(rows)


def get_cookie_file() -> str | None:
    """
    Return path to a fresh Netscape cookie file.
    Caches the file for COOKIE_TTL seconds before re-extracting.
    Returns None if Firefox cookies aren't available or empty.
    """
    now = time.time()

    # Return cached if still fresh
    if (
        _cookie_cache["path"]
        and os.path.exists(_cookie_cache["path"])
        and (now - _cookie_cache["timestamp"]) < _COOKIE_TTL
    ):
        return _cookie_cache["path"]

    db_path = _find_firefox_cookies_db()
    if not db_path:
        return None

    cookie_file = tempfile.mktemp(prefix="aquamusic-cookies-", suffix=".txt")
    try:
        count = _extract_cookies(db_path, cookie_file)
        if count == 0:
            if os.path.exists(cookie_file):
                os.unlink(cookie_file)
            return None
        _cookie_cache["path"] = cookie_file
        _cookie_cache["timestamp"] = now
        return cookie_file
    except Exception as e:
        print(f"[Cookies] Failed to extract cookies: {e}")
        if os.path.exists(cookie_file):
            try:
                os.unlink(cookie_file)
            except OSError:
                pass
        return None


